// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injection

import (
	"database/sql"
	"github.com/ZAF07/tigerlily-e-bakery-payment/internal/config"
	"github.com/ZAF07/tigerlily-e-bakery-payment/internal/injection/providers"
)

// Injectors from wire.go:

func GetGeneralConfig() *config.GeneralConfig {
	generalConfig := providers.GeneralConfigProvider()
	return generalConfig
}

func GetPaymentDBInstance() *sql.DB {
	db := providers.PaymentDBInstanceProvider()
	return db
}

func GetStripeServiceConfig() *config.StripeService {
	stripeService := providers.StripeConfigProvider()
	return stripeService
}
